In [1]:
from ensmallen_graph.datasets.linqs import Cora

In [2]:
cora = Cora()

In [9]:
%%timeit
cora.link_prediction_ids(42, batch_size=2**20, return_edge_types=True, shuffle=False)

19.7 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
import numpy as np
from collections import Counter
Counter((np.arange(1000)* 3456 +  45) % 2700)

Counter({45: 40,
         801: 40,
         1557: 40,
         2313: 40,
         369: 40,
         1125: 40,
         1881: 40,
         2637: 40,
         693: 40,
         1449: 40,
         2205: 40,
         261: 40,
         1017: 40,
         1773: 40,
         2529: 40,
         585: 40,
         1341: 40,
         2097: 40,
         153: 40,
         909: 40,
         1665: 40,
         2421: 40,
         477: 40,
         1233: 40,
         1989: 40})

In [12]:
cora.link_prediction_ids(42, batch_size=2**20, return_edge_types=True, shuffle=False)

(array([1045, 3177, 3003, ..., 1088, 1023, 2748], dtype=uint32),
 None,
 array([3356,  233,  111, ..., 1032, 4091, 1647], dtype=uint32),
 None,
 array([1, 1, 1, ..., 1, 0, 1], dtype=uint16),
 array([ True,  True,  True, ..., False, False, False]))

In [6]:
Counter(nodes)

NameError: name 'nodes' is not defined